[platformio]
default_envs = esp32-c6
src_dir = src

[env:esp32-c6]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LV_CONF_SKIP
    -D LV_USE_USER_DATA=1
    -D CORE_DEBUG_LEVEL=0
    -D LV_USE_LOG=0
    -D LV_USE_ASSERT_NULL=0
    -D LV_USE_ASSERT_MALLOC=0
    -D LV_USE_ASSERT_STYLE=0
    -D LV_USE_ASSERT_MEM_INTEGRITY=0
    -D LV_USE_ASSERT_OBJ=0
    -D LV_FONT_MONTSERRAT_16=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_SIMSUN_16_CJK=1

lib_deps = 
    lvgl/lvgl@8.4.0
    moononournation/GFX Library for Arduino
