[platformio]
default_envs = esp32-c6
src_dir = src

[env:esp32-c6]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LV_CONF_SKIP
    -D LV_USE_USER_DATA=1
    -D LV_FONT_MONTSERRAT_16=1
    -D LV_FONT_MONTSERRAT_24=1
    -D LV_FONT_MONTSERRAT_28=1

lib_deps = 
    lvgl/lvgl@8.4.0
    moononournation/GFX Library for Arduino
    koendv/cst816t
